name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: jodersky/setup-mill@master
        with:
          mill-version: 0.9.5
      - name: Compile
        run: mill __.compile
      - name: Test
        run: mill __.test